modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mixins]]
    config="backpack_side_gui.mixins.json"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile="icon.png"
    authors="${mod_authors}"
    description='''${mod_description}'''

[[dependencies.backpack_side_gui]]
    modId="neoforge"
    type="required"
    versionRange="[21.1,21.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.backpack_side_gui]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.backpack_side_gui]]
    modId="curios"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.backpack_side_gui]]
    modId="jei"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.backpack_side_gui]]
    modId="sophisticatedbackpacks"
    type="required"
    versionRange="[3.25.0,)"
    ordering="AFTER"
    side="BOTH"
